### PR TITLE
New annotations

### PR DESCRIPTION
**Pull request by abeaumont**
Complete annotations for tokens somehow related with cyclomatic complexity (with whatever definition we end up choosing at the end), except for the Assert one, since it seems to be showing a rather weird behaviour (appearing as an identifier in the native ast, or not appearing at all) and some complex cases that are marked as such in the code.

### CODE REVIEW

**Comment by smola** [comment]
This SDK API update needs to be merged first: https://github.com/bblfsh/java-driver/pull/16
And then this PR will need rebase.

**Comment by abeaumont** [comment]
Rebased

**Comment by smola** [comment]
@abeaumont rebase again?

**Comment by abeaumont** [comment]
rebased again

**Pull request merged**
