### PR TITLE
new fixtures for semantic UAST

### PR DESCRIPTION
**Pull request by dennwc**
Signed-off-by: Denys Smirnov <denys@sourced.tech>

### CODE REVIEW

**Comment by juanjux** [comment]
There should be a test with an interface, I think (in u2_type_ category?).

**Comment by dennwc** [comment]
@juanjux Good point!

**Comment by juanjux** [comment]
I also miss tests for lambda and inner classes (sorry for not noticing the previous time, too many fixtures today and my eyes start to cross...).

**Comment by juanjux** [comment]
Closing, superseded by #70.

**Pull request closed without merging**
